/*
 * jPanel19.java
 *
 * Created on July 12, 2005, 12:42 PM
 */

package prac;

/**
 *
 * @author  root
 */
public class jPanel19 extends javax.swing.JPanel {
    
    /** Creates new form jPanel19 */
    public jPanel19() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        setLayout(new java.awt.BorderLayout());
        
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
